### ISSUE TITLE
Function 4 - show_fit

### ISSUE THREAD

**Issue by sbabicki** [UBC-MDS/kmeaningful#8]

**Comment by trevorki** [comment]
I'm unclear about the purpose of this function. Should it :

**a.**  take in (processed data X) and (k), fit the model, then plot points coloured by cluster. 

**b.**  take in (processed data X), (a list of centroids) and (a list of cluster labels), then plot points coloured by cluster and labeled cluster label.

I think option (b) might work better because this would allow a user to use the model as in option (a) PLUS they could fit their model on some data then use this function to plot how new data is clustered.

**Comment by mikelynch416** [comment]
When I first thought of the idea for this function I was thinking along the lines of (a) but now that I think about it I'm leaning towards (b) beacause as you said it would allow us to see how new data points get clustered.

**Comment by sbabicki** [comment]
I like option b better. You can create an additional wrapper function to fit the model and then visualize by calling the two functions. It's best to keep each main function focused on only one specific thing.

**Comment by trevorki** [comment]
OK I'll update the docstring

**Comment by trevorki** [comment]
oops closed by mistake

**Comment by mikelynch416** [comment]
As we discussed during the lab this afternoon, we should consider changing the inputs for this function to take in the original data X, the list of cluster labels and the list of cluster centers (as an optional argument). This way the function would by default plot just the points from X coloured by their cluster labels, but if the cluster centers are also included they could be plotted too ex. as a star on the plot
